site_name: 爬虫逆向文章库
site_url: https://sunxhap.github.io/record_points/
docs_dir: docs

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang: zh
  - awesome-pages  # 自动生成所有导航

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

extra_css:
  - extra.css
