name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main        # 如果你的主分支是 master，改成 master
    paths-ignore:
      - 'README.md'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs-material mkdocs-awesome-pages-plugin

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force